[features]
seeds = false
skip-lint = false
[programs.localnet]
bonking = "Gx2UZFaDLEw3XQZdrdrTEEGfEBP9itEHuE4xpdGFJDUJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/anchor/idl && cp target/idl/bonking.json app/src/anchor/idl/bonking.json"
copy-types = "mkdir -p app/src/anchor/types && cp target/types/bonking.ts app/src/anchor/types/bonking.ts"
