# yaml-language-server: =https://json.schemastore.org/github-workflow.json
---
name: "Program Tests"
on:
    push:
        paths:
            - 'tests/**'
            - 'programs/**'
            - '.github/workflows/program-tests.yml'
jobs:
    just-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: nightly
            - name: Install Solana
              run: |
                sh -c "$(curl -sSfL https://release.solana.com/v1.15.1/install)"
            - name: Generate keyfile
              run: |
                export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
                solana-keygen new --outfile ~/.config/solana/id.json
            - name: Install Anchor
              run: npm i @coral-xyz/anchor-cli -g
            - name: Run tests
              run: |
                cd ${{ github.workspace }}
                export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
                anchor test
